name: Multi-Platform Workflow

on:
  pull_request:
    branches: main

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display OS Information
        run: uname -a

      - name: Create and Display File
        run: |
          echo "Hello from Ubuntu!" > ubuntu.txt
          cat ubuntu.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display OS Information
        run: systeminfo

      - name: Create and Display File
        run: |
          echo "Hello from Windows!" > windows.txt
          type windows.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display OS Information
        run: uname -a

      - name: Create and Display File
        run: |
          echo "Hello from macOS!" > macos.txt
          cat macos.txt
